#!/usr/bin/env python3
"""
Plotting script for LLM database security evaluation.
Builds plots from analysis/report.json generated by analysis/stats.py.
"""

import argparse
import json
import os
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np


plt.style.use("seaborn-v0_8")


def _load_report(path: str) -> Dict:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _flatten_for_plot(report: Dict) -> List[Tuple[str, str, float, float, float]]:
    rows = []
    for config, goals in report.items():
        for goal, values in goals.items():
            rows.append(
                (
                    config,
                    goal,
                    values.get("mean_asr", 0.0),
                    values.get("lower_ci", 0.0),
                    values.get("upper_ci", 0.0),
                )
            )
    return rows


def plot_config_asr(report: Dict, out_dir: str) -> None:
    configs = sorted(report.keys())
    means = []

    for cfg in configs:
        entries = list(report[cfg].values())
        if not entries:
            means.append(0.0)
            continue
        means.append(sum(item["mean_asr"] for item in entries) / len(entries))

    fig, ax = plt.subplots(figsize=(10, 5))
    bars = ax.bar(configs, means, color="#1f77b4", alpha=0.85)
    ax.set_ylim(0, 1)
    ax.set_title("Mean ASR by Configuration")
    ax.set_xlabel("Configuration")
    ax.set_ylabel("ASR")
    ax.grid(axis="y", alpha=0.3)

    for bar, value in zip(bars, means):
        ax.text(bar.get_x() + bar.get_width() / 2, value + 0.01, f"{value:.2f}", ha="center", fontsize=8)

    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "asr_by_config.png"), dpi=200)
    plt.close(fig)


def plot_goal_heatmap(report: Dict, out_dir: str) -> None:
    configs = sorted(report.keys())
    goals = sorted({goal for cfg in report.values() for goal in cfg.keys()})

    matrix = np.zeros((len(configs), len(goals)))
    for i, cfg in enumerate(configs):
        for j, goal in enumerate(goals):
            matrix[i, j] = report.get(cfg, {}).get(goal, {}).get("mean_asr", 0.0)

    fig, ax = plt.subplots(figsize=(12, 6))
    image = ax.imshow(matrix, cmap="RdYlGn_r", aspect="auto", vmin=0, vmax=1)
    ax.set_xticks(np.arange(len(goals)))
    ax.set_xticklabels(goals, rotation=45, ha="right")
    ax.set_yticks(np.arange(len(configs)))
    ax.set_yticklabels(configs)
    ax.set_title("ASR Heatmap: Configuration x Goal")

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, f"{matrix[i, j]:.2f}", ha="center", va="center", fontsize=8)

    plt.colorbar(image, ax=ax, label="ASR")
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "asr_heatmap.png"), dpi=200)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Render plots from analysis JSON report")
    parser.add_argument("--input", default="analysis/report.json", help="Path to report JSON")
    parser.add_argument("--out-dir", default="analysis/plots", help="Output directory for plots")
    args = parser.parse_args()

    report = _load_report(args.input)
    os.makedirs(args.out_dir, exist_ok=True)

    plot_config_asr(report, args.out_dir)
    plot_goal_heatmap(report, args.out_dir)

    print(f"Wrote plots in {args.out_dir}")


if __name__ == "__main__":
    main()
